export const CERTIFICATES_CONTENT = {
  intro:
    'Academic credentials, professional training, and online certifications that shaped my journey in software engineering and artificial intelligence.',

  certificates: [
    {
      id: 'saba-cs-degree',
      title: "Bachelor's Degree in Computer Science",
      organization: 'Saba University – Ministry of Higher Education',
      type: 'Degree',
      category: 'Academic',
      date: '2026',
      duration: '4 Years',
      location: 'Kandahar, Afghanistan',
      description:
        "Awarded a Bachelor's degree in Computer Science in recognition of successfully fulfilling the academic requirements of the Department of Information Technology, Faculty of Computer Science, with all associated privileges and obligations.",
      skills: [
        'Computer Science',
        'Information Technology',
        'Software Development',
        'Programming',
        'Database Management',
        'Web Development',
        'Computer Networks',
      ],
      image: '/cer/cs.jpg',
    },
    {
      id: 'luilala-web-dev',
      title: 'Practical Training in Web Development',
      organization: 'Luilala Soft',
      type: 'Training',
      category: 'Training',
      date: 'August 19, 2026',
      duration: 'March 23, 2025 – August 26, 2026',
      location: 'Afghanistan',
      description:
        'Successfully completed practical training in Web Development, gaining hands-on experience in JavaScript, Python, and Mobile App Development, while contributing to the design and development of various Web Applications, Mobile Applications, and Management Systems.',
      skills: [
        'Web Development',
        'JavaScript',
        'Python',
        'Mobile App Development',
        'Web Applications',
        'Mobile Applications',
        'Management Systems',
      ],
      image: '/cer/lui.jpg',
    },
    {
      id: 'umd-ai-career',
      title: 'AI and Career Empowerment',
      organization: 'University of Maryland – Robert H. Smith School of Business',
      type: 'Course',
      category: 'AI & ML',
      date: 'August 22, 2026',
      duration: 'Non-credit Course',
      location: 'University of Maryland, USA',
      description:
        'Successfully completed the AI and Career Empowerment non-credit course offered through the University of Maryland Robert H. Smith School of Business.',
      skills: [
        'Artificial Intelligence',
        'Career Development',
        'AI Applications',
        'Professional Skills',
      ],
      image: '/cer/aa.png',
    },
    {
      id: 'deeplearning-ai-python',
      title: 'AI Python for Beginners',
      organization: 'DeepLearning.AI – Coursera',
      type: 'Online Course',
      category: 'AI & ML',
      date: 'August 28, 2025',
      duration: 'Online Course',
      location: 'Online',
      description:
        'Successfully completed the AI Python for Beginners online course, gaining foundational knowledge of Python programming and its application in Artificial Intelligence.',
      skills: [
        'Python',
        'Artificial Intelligence',
        'Programming Fundamentals',
        'AI Fundamentals',
      ],
      image: '/cer/bb.png',
    },
    {
      id: 'ibm-ai-essentials',
      title: 'Artificial Intelligence Essentials V2',
      organization: 'IBM',
      type: 'Professional Certificate',
      category: 'AI & ML',
      date: 'February 26, 2025',
      duration: 'Professional Certificate',
      location: 'Online',
      description:
        'Successfully completed the requirements for Artificial Intelligence Essentials V2, demonstrating foundational knowledge and understanding of Artificial Intelligence concepts and applications.',
      skills: [
        'Artificial Intelligence',
        'AI Fundamentals',
        'Machine Learning Fundamentals',
        'Generative AI',
        'AI Applications',
      ],
      image: '/cer/cc.jpg',
    },
  ],
}
